version: '3'
services:
  Elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
        node.name: mynode
      #network.host: ${[_local_,_site_]}  
    ports:
      - 9200:9200
    networks:
      - mynet             
volumes: 
  esdata: 
networks:
  mynet:     